Create security-guidelines.md
status-im/handbook.status.im pull request #36
Opened 2021-10-27 19:04 UTC by monicazng

2021-11-01 17:54 UTC, corpetty requested changes

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
also include #security-internal for anything that is more private, or #security for more broad, public questions.

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
this should stay updated as we transition to various places. I'll continue to add resources for you to add.

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
the security@status.im email is also available.

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
probably link [security-internal](github.com/status-im/security-internal) and [status-security](github.com/status-im/status-security) resources, which hold internal and public security information, respectively.

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
thoughts @status-im/security-internal on anything else to add or change?

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +Our password manager is Bitwarden; everyone is free to use it to store and secure passwords. You can request an invite from @terry.
all organizational passwords should be kept and shared here. So if you plan to store a Status related password, or get access to platforms that require username/passwords/2fa, then it should all be shared here. 

By signing up with the organization, you get the premium features, and can sign up with any email you like. That way if you ever leave Status you can take your password manager secrets with you, and you just lose access to Status related ones.

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
hardware security keys (yubikeys) can be expensed by a CC, and should be used for Github/Gsuite/Bitwarden.

2021-11-01 17:54 UTC, corpetty commented on src/settling-in/security-guidelines.md
> +
something regarding hardware wallets could also go here, maybe link the learn-up video here as well. 

https://www.youtube.com/watch?v=9nzqntuFR44

2021-11-03 13:00 UTC, monicazng commented on src/settling-in/security-guidelines.md
> +
This is great, adding it!

2021-12-13 11:49 UTC, serhanwbahar approved these changes

2022-01-10 14:20 UTC, OxFred approved these changes

2022-02-11 17:42 UTC, merged