Create traveling-for-status.md
status-im/handbook.status.im pull request #46
Opened 2021-10-27 19:40 UTC by monicazng

2021-11-08 11:59 UTC, Stefaniach requested changes

2021-11-08 11:59 UTC, Stefaniach commented on src/working-here/traveling-for-status.md
> +   * Hotel, flights, etc., room service, or in-room movies/entertainment.
room service (meals) within the $75 per day should be covered imo (cc @johannesmw ?)

2021-11-08 11:59 UTC, Stefaniach commented on src/working-here/traveling-for-status.md
> +   * Mobile, roaming, or hotspot connection fees.
Not sure about this one. People need to be connected to work and sometimes these expenses happen (e.g. long layovers, intercontinental trips when local SIM cards not available...)

2021-11-08 11:59 UTC, Stefaniach commented on src/working-here/traveling-for-status.md
> +Usually, the earlier you plan your trip, the cheaper and better it's going to be. We suggest preparing at least one month ahead to have enough time to communicate your plans and stay within budget.
I'd add here that we understand this is more difficult now during Covid.

2021-11-08 11:59 UTC, Stefaniach commented on src/working-here/traveling-for-status.md
> +* We usually travel in economy class fare with carry-on luggage included. You can add one checked luggage for trips longer than a week or when you're carrying additional baggage for Status.
this sounds a bit extreme? if someone needs a little more luggage to feel comfortable for a business trip I think we should just pay for the checked bag, no q asked.

2022-09-22 15:14 UTC, Terrytobin approved these changes

2022-09-22 15:14 UTC, merged