Create workspace-computers-and-devices.md
status-im/handbook.status.im pull request #49
Opened 2021-10-27 19:49 UTC by monicazng

2021-11-02 13:50 UTC, jakubgs reviewed
One thing you might want to do in these PRs is also edit [`src/SUMMARY.md`](https://github.com/status-im/handbook.status.im/blob/develop/src/SUMMARY.md). Since otherwise these pages are inaccessible. Read about it:

https://rust-lang.github.io/mdBook/format/summary.html

In general, if you just run `mdbook serve` and you edit `SUMMARY.md` it will also create the corresponding files.

2021-11-03 17:32 UTC, Stefaniach requested changes

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +   * Laptop: up to 2000 EUR
Suggest using USD

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +   * Mic and headphones: up to 100 EUR
USD

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +   * Keycard: ping @guylouis to get a code
would be cool to have a generic contact or channel (what if - God Forbids - Guy-Luis leaves?)

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +Check beforehand if there's already a suitable item in our [inventory](https://docs.google.com/spreadsheets/d/1A2jqn3Ch-zDyHFRnqMaoWwVHKBAPgH2p4sgEWk7Jwyo/edit?ts=5c2cbe52#gid=0). Also, consider refu
This has been used so very little (or maybe it's just my impression). It's also not making a lot of sense as we want to incentivise people to keep devices in the first place to reduce overhead. I'd consider removing entirely?

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +Check beforehand if there's already a suitable item in our [inventory](https://docs.google.com/spreadsheets/d/1A2jqn3Ch-zDyHFRnqMaoWwVHKBAPgH2p4sgEWk7Jwyo/edit?ts=5c2cbe52#gid=0). Also, consider refu
`consider refurbished devices and purchasing in trusted secondary markets for things that make sense. `
this is confusing to me -  'things that make sense' can mean something different to each individual. Could we list out some examples?

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +   1. Let your team lead and People Ops know the devices you will purchase two weeks before your start date, during your onboarding, or when you need them.
`Let your team lead and People Ops know the devices you will purchase two weeks before your start date, during your onboarding, or when you need them. `

` Let your team lead know the devices you will purchase ` would suffice - People Ops doesn't need to know, unless they have questions. Also, the three scenarios (2 weeks before, during onboarding or when you need' basically cover .... all the time someone works for us.

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +   * **What if I'm a German employee?**
missing **What if I am a CH employee**?

2021-11-03 17:32 UTC, Stefaniach commented on src/perks/computers-and-devices.md
> +      At the 3 year mark, if your device needs an upgrade, ping People Ops.
For anyone in engineering/R&D I recommend 2 years for a change (we can probably see the same pattern if we check laptop expenses from 2017 til now). Ops can do with 3 for sure.

2021-11-03 22:08 UTC, PabloMoralesMX commented on src/perks/computers-and-devices.md
> +Check beforehand if there's already a suitable item in our [inventory](https://docs.google.com/spreadsheets/d/1A2jqn3Ch-zDyHFRnqMaoWwVHKBAPgH2p4sgEWk7Jwyo/edit?ts=5c2cbe52#gid=0). Also, consider refu
I suggest also to remove "Also, consider refurbished devices and purchasing in trusted secondary markets for things that make sense. " as  the requirements to be met by secondary markets are unclear. I assume that the volume of secondary market usage is very low.

2021-11-03 22:13 UTC, PabloMoralesMX commented on src/perks/computers-and-devices.md
> +   1. Let your team lead and People Ops know the devices you will purchase two weeks before your start date, during your onboarding, or when you need them.
It seems to me that it would be good to clarify to be as follows: For additional funds per item or other equipment, you need to obtain a previous approval from your team lead and and add the approval details to your reimbursement.

2021-11-05 15:51 UTC, monicazng commented on src/perks/computers-and-devices.md
> +   * Keycard: ping @guylouis to get a code
I'll change it to: ping someone from the Keycard team using the #keycard channel instead :D

2021-11-05 15:53 UTC, monicazng commented on src/perks/computers-and-devices.md
> +Check beforehand if there's already a suitable item in our [inventory](https://docs.google.com/spreadsheets/d/1A2jqn3Ch-zDyHFRnqMaoWwVHKBAPgH2p4sgEWk7Jwyo/edit?ts=5c2cbe52#gid=0). Also, consider refu
This was included in the current article for testing phones, which is something we're considering reimbursable but not pre-approved in this new version. So maybe let's remove the entire paragraph yes.

2021-11-05 15:54 UTC, monicazng commented on src/perks/computers-and-devices.md
> +      At the 3 year mark, if your device needs an upgrade, ping People Ops.
I'll update the time then!

2022-02-01 15:53 UTC, merged